// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBscF7jto3agk8vn5CjvSdNkMigQ2KMnh8',
    appId: '1:1053907455233:web:94b17cafc0cbd68386df00',
    messagingSenderId: '1053907455233',
    projectId: 'pubsconnect-thesis',
    authDomain: 'pubsconnect-thesis.firebaseapp.com',
    databaseURL: 'https://pubsconnect-thesis-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pubsconnect-thesis.appspot.com',
    measurementId: 'G-00W7FYTQT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCInL8mlcLw2BBcG6R81tBNFffZJrqw1_Y',
    appId: '1:1053907455233:android:4cfa9eb3d521057986df00',
    messagingSenderId: '1053907455233',
    projectId: 'pubsconnect-thesis',
    databaseURL: 'https://pubsconnect-thesis-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pubsconnect-thesis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-TvKk7MVy8eHkeuuGDgd91w6l0HTcVYo',
    appId: '1:1053907455233:ios:238f02ca08a6275486df00',
    messagingSenderId: '1053907455233',
    projectId: 'pubsconnect-thesis',
    databaseURL: 'https://pubsconnect-thesis-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pubsconnect-thesis.appspot.com',
    androidClientId: '1053907455233-ejf27cc3s9dpht3f9548v4nffir02a1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.thesisPubsconnect',
  );
}
